// assets/js/data.js
window.PRODUCTS = [
  {
    id: "egg-roll",
    name: "Egg Roll",
    price: 20,
    packSize: 5,
    images: [
      "assets/images/Eggroll1.PNG",
      "assets/images/egg-roll-2.jpg",
      "assets/images/egg-roll-3.jpg",
    ],
    description: "A golden-brown dough wrapped around boiled egg. Rich, fluffy and crunchy crust.",
    ingredients: ["flour", "sugar", "butter", "eggs", "salt", "baking powder", "oil", "milk"],
    reheating: "Store in the fridge. Microwave ~10s until warm.",
    maxPacks: 8,
  },
  {
    id: "meat-pie",
    name: "Meat Pie",
    price: 25,
    packSize: 5,
    images: [
      "assets/images/meatpie1.PNG",
      "assets/images/meatpie2.PNG",
      "assets/images/meatpie.jpg",
    ],
    description: "Flaky buttery dough with minced meat, potato and carrot filling cooked in rich flavours.",
    ingredients: ["flour", "butter", "ground beef", "potatoes", "onions", "carrot", "eggs", "spices"],
    reheating: "Store in the fridge. Microwave 15–40s until warm.",
    maxPacks: 8,
  },
  {
    id: "chicken-pie",
    name: "Chicken Pie",
    price: 25,
    packSize: 5,
    images: [
      "assets/images/chickenpie2.jpg",
      "assets/images/chickenpie1.PNG",
      "assets/images/chickenpie3.PNG",
    ],
    description: "Flaky buttery dough with chicken, potato, carrot filling cooked in rich flavours.",
    ingredients: ["flour", "butter", "chicken", "potato", "carrot", "onions", "eggs", "spices"],
    reheating: "Store in the fridge. Microwave 15–40s until warm.",
    maxPacks: 8,
  },
  {
    id: "sausage-roll",
    name: "Sausage Roll",
    price: 20,
    packSize: 5,
    images: [
      "assets/images/sausage-roll.JPG",
      "assets/images/sausage-roll1.JPG",
      "assets/images/sausage-roll3.jpg",
    ],
    description: "A flavourful seasoned sausage meat in a buttery flaky dough.",
    ingredients: ["flour", "butter", "eggs", "sausage meat", "spices"],
    reheating: "Store in the fridge. Microwave 15–40s until warm.",
    maxPacks: 8,
  },
  {
    id: "sausage-bread-roll",
    name: "Sausage Bread Roll",
    price: 20,
    packSize: 5,
    images: [
      "assets/images/sausage.jpg",
      "assets/images/sausage1.PNG",
      "assets/images/sausage2.jpg",
    ],
    description: "Juicy chicken hotdogs wrapped in freshly baked fluffy bread rolls.",
    ingredients: ["flour", "butter", "milk", "chicken sausage", "eggs", "yeast"],
    reheating: "Store in the fridge. Microwave 15–40s until warm.",
    maxPacks: 8,
  },
  {
    id: "fish-roll",
    name: "Fish Roll",
    price: 20,
    packSize: 5,
    images: [
      "assets/images/fishroll2.jpg",
      "assets/images/fishroll1.jpg",
      "assets/images/fishroll3.jpg",
    ],
    description: "Delicious, crunchy dough pastries with fish filling and spices.",
    ingredients: ["flour", "butter", "egg", "fish", "spices"],
    reheating: "Store in the fridge. Microwave 15–40s until warm.",
    maxPacks: 8,
  },
];
